<?php
require_once ( '../lib/Utility.php' );
require_once ( '../lib/pagecontent.php' );
require_once ( '../lib/pagelanguage.php' );
require_once ( '../lib/session.php' );

$menuId = Utility::getValue ( 'menu_id' );
$action = Utility::getValue ( 'action' );
$content = Utility::getValue ( 'txt_content' );
$title = Utility::getValue ( 'txt_title' );
$pageId = Utility::getValue ( 'page_id' );
$arrIds = explode ( '_', $menuId );
if ( isset ( $arrIds [ 2 ] ) && !empty ( $arrIds [ 2 ] ) ) {
  $pageId = $arrIds [ 2 ];
}

$ssnID = Utility::getValue ('medtel_ssn');
$langId = Utility::getValue ('lang_id');
$companyId = $_SESSION[$ssnID]["company"]["id"];
$objLang = new PageLanguage ( $companyId );
if ( empty ($langId) ) $langId = $objLang->getDefaultLanguage();
$tabs = $objLang->getTabs ($langId);

if ( $pageId == 'root16' ) $pageIndex = 'aboutus';
else if ( $pageId == 'root17' ) $pageIndex = 'contactus';
else if ( $pageId == 'root18' ) $pageIndex = 'terms';
else if ( $pageId == 'root19' ) $pageIndex = 'privacy';
else if ( $pageId == 'root20' ) $pageIndex = 'sitemap';
else if ( $pageId == 'root28' ) $pageIndex = 'custspt';
else if ( $pageId == 'root29' ) $pageIndex = 'mketspt';
else if ( $pageId == 'root30' ) $pageIndex = 'tchnspt';
else if ( $pageId == 'root31' ) $pageIndex = 'newsletter';

$success = '';
if ( isset ( $pageIndex ) && !empty ( $pageIndex ) ) {
  $objPage = new PageContent ( $companyId, $langId );
  if ( isset ( $action ) && $action == 'update' ) {
    $objPage->updatePageContentByIndex ( $pageIndex, $content, $title );
    $success = "Content has been successfully saved.";
  }
  $arrRes = $objPage->getPageContentByIndex ( $pageIndex ); 
  $content = $arrRes [ 'content' ];
  $title = $arrRes [ 'title' ];
}
?>
<html>
<head>
<title>Medtel Australia - Html Editor</title>
<meta http-equiv="content-type" content="text/html;charset='utf-8'">
<meta http-Equiv="Cache-Control" Content="no-cache">
<meta http-Equiv="Pragma" Content="no-cache">
<meta http-Equiv="Expires" Content="0">
<script language='javascript'>
function setLanguageId (obj) {
  document.form_rte.lang_id.value = obj.id;
  document.form_rte.submit();
}
</script>
<style>
#g_tabs_pane {
  /* height: 400px; */
  overflow: auto;
  margin-top: 4px;
}

.bogoTabsActiveLabel {
  text-decoration: none;
  padding: 4px 5px 4px 4px;
  font-weight: bold;
  border-style: outset;
  border-left: 1px solid black;
  border-right: 1px solid black;
  border-top: 2px solid #FFD13C;
  border-bottom: 1px solid black;
  font-size: 0.8em;
  color: #fff;
  background-color: #7387A2;
  margin-left: 2px;
  cursor:pointer;
}

.bogoTabsInactiveLabel {
  font-size: 0.8em;
  text-decoration: none;
  padding: 4px 5px 4px 4px;
  font-weight: normal;
  border-width: 1px;
  border-color: black;
  border-style: inset;
  color: #000;
  background-color: #CCCCCC;
  margin-left: 2px;
  cursor:pointer;
}
</style>
</head>
<body style='margin-top:2px;'>
<?=$tabs;?>
<div style='color:red;font-weight:bold;font-size:11pt;'><?=$success;?></div>
<form name='form_rte' action='pageedit.php' method="post" onsubmit="return false;">
<table><tr><td>Link Title:</td><td>
<input type='text' name='txt_title' value='<?=$title;?>'>(Please input the link title for this language)
</td></tr>
<?php
if ($pageId == 'root20'){
?>
<tr><td colspan='2'><b>Note: The sitemap page is automatically generated by system. You don't need to edit. </b></td></tr>
<?php
}
?>
</table>
<?php
if ($pageId == 'root20'){
  echo $content;
} else {
?>
<textarea name='txt_content' id='txt_content' style='display:none'><?=$content;?></textarea>
<!-- Include the Free Rich Text Editor Runtime -->
<script src="js/richtext.js" type="text/javascript" language="javascript"></script>
<!-- Include the Free Rich Text Editor Variables Page -->
<script src="js/config.js" type="text/javascript" language="javascript"></script>
<!-- Initialise the editor -->
<script>
var initContent = document.getElementById('txt_content').value;
initRTE(initContent, "", '460px');
function saveHtmlContent(){
  var rteContent = getXHTML(trim(document.getElementById(rteName).contentWindow.document.body.innerHTML));
  document.getElementById('txt_content').value = rteContent;
  document.form_rte.action.value = 'update';
  document.form_rte.submit ();
}
</script>
<?php
}
?>
<input type="hidden" name="page_id" value="<?=$pageId;?>">
<input type="hidden" name="medtel_ssn" value="<?=$ssnID;?>">
<input type="hidden" name="lang_id" value="<?=$langId;?>">
<input type="hidden" name="action" value="">
<?php
if ($pageId == 'root20'){
?>
<input type="button" onclick="document.form_rte.action.value = 'update';document.form_rte.submit();" value="Save Title" >
<?php
} else {
?>
<input type="button" onclick="saveHtmlContent();" value="Save Content" >
<?php
}
?>
</form>
</body>
</html>
